version: '3.8'

services:
  vpn-bot:
    build: .
    container_name: no_logs_bot
    ports:
      - "8443:8000"
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/letsencrypt/live/nologs.site/fullchain.pem:/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/nologs.site/privkey.pem:/certs/privkey.pem:ro
    environment:
      - PYTHONPATH=/app
    env_file:
      - .env
    restart: unless-stopped
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000
      --ssl-certfile /certs/fullchain.pem
      --ssl-keyfile /certs/privkey.pem

  xray:
    image: teddysun/xray
    container_name: xray
    volumes:
      - ./xray:/etc/xray
    ports:
      - "443:443"
    restart: unless-stopped
